// <auto-generated />
using CDmoment3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CDmoment3.Migrations
{
    [DbContext(typeof(CdDataContext))]
    [Migration("20200316113933_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CDmoment3.Models.ArtistData", b =>
                {
                    b.Property<int>("ArtistDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Artistnamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistDataId");

                    b.ToTable("ArtistData");
                });

            modelBuilder.Entity("CDmoment3.Models.CdData", b =>
                {
                    b.Property<int>("CdDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistDataId")
                        .HasColumnType("int");

                    b.Property<string>("Detaljer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skivnamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdDataId");

                    b.HasIndex("ArtistDataId");

                    b.ToTable("CdData");
                });

            modelBuilder.Entity("CDmoment3.Models.CdData", b =>
                {
                    b.HasOne("CDmoment3.Models.ArtistData", "ArtistData")
                        .WithMany("CDskivorData")
                        .HasForeignKey("ArtistDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
